version: '3.8'

services:
  backend:
    build: ./backend
    container_name: event-system-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/eventsdb
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=eventsdb
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
    depends_on:
      - mongodb
      - postgres
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=eventsdb

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eventsdb
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
